# Generated by Django 5.2.10 on 2026-01-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
